name: Backend CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  backend-tests:
    name: Backend CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Force Python Version
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Validate Python Version
        run: |
          echo "Validated Python version:" $(python --version)
          echo "PYTHONPATH:" $PYTHONPATH

      - name: Install dependencies
        run: pip install -r backend/requirements.txt
